name: Deploy to Github Pages
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'AbdelrhmanSaid'
        reponame: 'me'
        token: ${{ secrets.GITHUB_TOKEN }}
        gitemail: 'abdelrhmansaidzaki@hotmail.com'
        gitname: 'Abdelrhman Said'
        gitmsg: 'Deploy to Github pages'
        cname: 'abdelrhmansaid.me'
        
